package Strony;
import FabrykaMain.tworzStrony;
import java.util.Random;

public class Informacyjna extends Strona implements tworzStrony {
    public Informacyjna(){
        Random r = new Random();
        int x = 0;
        String a ="&nbsp Kot domowy (Felis catus, również Felis silvestris catus lub Felis (silvestris) domesticus) – "
                + "udomowiony gatunek ssaka z rzędu drapieżnych z rodziny kotowatych. Koty zostały udomowione około 9500 lat temu i są obecnie najpopularniejszymi zwierzętami domowymi na świecie. "
                + "Gatunek prawdopodobnie pochodzi od kota nubijskiego, przy czym w Europie krzyżował się ze żbikiem. Jest uznawany za gatunek inwazyjny.\n"
                + "Przodkiem kota domowego jest kot nubijski – według poglądów większości współczesnych naukowców różnice pomiędzy kotem domowym i nubijskim są tak niewielkie, że należą one do tego samego podgatunku. Istnieją rozbieżności w kwestii daty udomowienia kota. Większość źródeł sugeruje lata 4000–3700 p.n.e., a miejscem, w którym miało do tego dojść, była Nubia. "
                + "Istnieją jednak dowody (grób mężczyzny z kotem[6] z Cypru sprzed ok. 7500 r. p.n.e.), że domestykacja kota zaczęła się znacznie wcześniej i trwała kilka tysięcy lat, a jej miejscem był obszar Żyznego Półksiężyca. Już ok. 2000 r. p.n.e. kot był pospolicie hodowany w Egipcie. Początkowo był obiektem kultu, wiązano go z boginią Bastet, a zwłoki kotów mumifikowano. Później zaczęto wykorzystywać go do tępienia gryzoni.\n" 
                + "Wyhodowano wiele ras kota domowego, różniących się ubarwieniem, wielkością i długością włosów; współczesne wzorce niektórych starszych ras znacznie odbiegają od ich wcześniejszych cech (jak w przypadku kotów perskich czy syjamskich)."
                + "Znaczna liczba kotów domowych żyje samodzielnie w miastach (w Polsce są to tzw. koty piwniczne lub dachowce).\n"
                + "Koty żyjące na wolności dożywają średnio do 8 lat, natomiast koty trzymane w domu osiągają wiek do 20 lat. Na długość życia wpływa szereg czynników, takich jak: płeć, styl życia czy zwyczaje. Najdłużej żyjącym kotem według Księgi rekordów Guinnessa była kotka imieniem Creme Puff (1967–2005), która przeżyła 38 lat i 3 dni[7].\n" 
                + "Małe kocięta rozwijają się szybko. Stają się w pełni samodzielne w wieku od 10 do 12 tygodni i wtedy mogą trafić do nowych właścicieli. Gdy mają około 3 miesięcy kotka przestaje się nimi interesować i zmusza je do samodzielności. W wieku około 5 miesięcy kociaki wymieniają zęby na stałe. Dzieciństwo kończy się z uzyskaniem dojrzałości płciowej. W tym okresie może pojawić się pierwsza ruja, a kot zaczyna oznaczać swoje terytorium.\n"
                + "Wyraźne objawy starości pojawiają się zwykle po 10 roku życia: coraz częściej pojawia się kamień nazębny, osłabia się wzrok, słuch i węch, stają się powolne oraz słabe. Stare koty są bardzo wrażliwe na zmiany środowiskowe i stres.<br/>";
        String b ="&nbsp Lew afrykański, lew (Panthera leo) – mięsożerny gatunek ssaka lądowego z rodziny kotowatych, drugi po tygrysie – co do wielkości – wśród czterech ryczących wielkich kotów. Jedyny kot żyjący w zorganizowanych grupach socjalnych, zaliczany do tzw. wielkiej piątki Afryki – pięciu najbardziej niebezpiecznych zwierząt afrykańskich (słoń, nosorożec, bawół, lew i lampart). Samiec lwa, łatwo rozpoznawalny po grzywie, może ważyć 150-200 kg. Największy znany samiec ważył 375 kg, był to lew o imieniu Simba, żył on do 1970 roku w Colchester Zoo. "
                + "Samice są znacznie mniejsze, ważą 120–180 kg (największe 185 kg) i nie mają grzywy. Samce zajmują się zdobywaniem i obroną terytorium oraz ochroną stada i zapładnianiem samic. Samice polują i opiekują się lwiątkami. Lwy zamieszkiwały niegdyś Afrykę, Azję i Europę, a jeśli uznać lwy amerykańskie za podgatunek Panthera leo – to również Amerykę Północną i Południową. Współcześnie występują tylko w Afryce, gdzie są narażone na wyginięcie i szczątkowo w Indiach, gdzie ich stan liczebny określony został jako krytyczny.\n"
                + "Etymologia nazw lew i Panthera leo nie jest jednoznacznie wyjaśniona. Słowo leo pochodzi od łacińskiego leō, leōnis, które z kolei wywodzi się ze starogreckiego leōn/λεων[6]. Dalszych źródeł autorzy dopatrują się w języku hebrajskim i staroegipskim.\n" 
                + "Lew jako gatunek został opisany naukowo przez Linneusza pod nazwą Felis leo Linnaeus, 1758, następnie przeniesiony do rodzaju Leo Brehm, 1829, a w końcu zaliczony przez Pococka do rodzaju Panthera w 1930. Pochodzenie słowa Panthera jest często wyjaśniane jako złożenie greckiego pan- oznaczającego wszech- i thēr oznaczającego zwierzę, co miałoby nawiązywać do dawnego szerokiego zasięgu występowania lwów. Online Etymology Dictionary wyjaśnienie takie uważa za etymologię ludową i dopatruje się pochodzenia słowa panthera z orientalnych określeń ubarwienia zwierzęcia."
                + "Wielkie koty, do których zaliczany jest lew, wywodzą się z jednej linii ewolucyjnej, określanej nazwą Pantherinae. Należą do niej rodzaje Panthera i Neofelis i Pardofelis. Dotychczas nie znaleziono ich ostatniego wspólnego przodka, ale z badań mtDNA wynika, że ich linie rozwojowe oddzieliły się ok. 6 mln lat temu. Znalezione ślady kopalne sugerują, że przedstawiciele kotów podobnych do współczesnego lwa pojawili się w Afryce Wschodniej w późnym pliocenie (5–1,8 mln lat temu)[9]. Najstarsze szczątki zaliczane do linii rozwojowej lwa, datowane na ok. 3,5 mln lat, odnaleziono w Laetoli w Tanzanii[10]. Niektórzy naukowcy klasyfikują go do gatunku Panthera leo, ale stanowisko takie nie jest powszechnie akceptowane ze względu na wiele niejasności.\n" 
                + "Naukowcy są zgodni co do tego, że właściwy Panthera leo żył w Afryce co najmniej 1,5 mln lat temu i rozprzestrzenił się po całym kontynencie. Wczesnoplejstoceńskie prymitywne lwy opisywane początkowo jako P. l. fossilis pojawiły się we wczesnym i środkowym plejstocenie, a ok. 700 tysięcy lat temu migrowały do Europy i Azji[12][13]. W późnym plejstocenie (100–10 tys. lat temu) były najbardziej rozprzestrzenionym dużym ssakiem lądowym. Zasięg ich występowania obejmował Afrykę, Eurazję, Amerykę Północną i Południową. W czasach historycznych (2 tys. lat temu) zamieszkiwały już tylko Bałkany (Bułgaria, Macedonia i lasy Grecji) przez Persję aż do Indii i prawie całą Afrykę.\n" 
                + "Lew był kiedyś – jak większość współczesnych drapieżników – gatunkiem kosmopolitycznym. Gwałtowne przemiany antropogeniczne w przeciągu ostatnich kilku tysięcy lat obecnej epoki holoceńskiej spowodowały wymarcie populacji lwów na wielu obszarach, w wyniku czego lew jest obecnie gatunkiem reliktowym, zagrożonym przede wszystkim ze strony człowieka.\n" 
                + "Z badań genetycznych wynika, że niezależnie wyewoluowały dwie odrębne linie lwa. Jedna reprezentowana przez wymarłe pod koniec ostatniej epoki lodowcowej (ok. 10 tys. lat temu) lwy jaskiniowe i lwy amerykańskie, druga – przez współczesnego Panthera leo."
                + "Pierwotny zasięg występowania lwów obejmował tereny Eurazji od Portugalii po Indie, większą część Afryki oraz Amerykę – od północy po Peru. Stopniowo eliminowany z Ameryki i Europy, ostatni obszar występowania w Europie to Kaukaz, gdzie spotykano go jeszcze w X w. n.e. Pod koniec XIX i na początku XX w. wyginęły w Afryce Północnej i na Bliskim Wschodzie. Z pierwotnego zasięgu został wyeliminowany przez czynniki środowiskowe i działalność człowieka i ograniczony wyłącznie do terenów Afryki i Indii. Większość obecnej populacji szacowanej pomiędzy 16000 a 30000 osobników występuje we wschodniej i południowej części Afryki.\n" 
                + "Na przekór popularnemu określeniu \"król dżungli\" lew jest zwierzęciem otwartych równin. Można go spotkać w całej Afryce, głównie subsaharyjskiej, z wyjątkiem terenów pustynnych i lasów równikowych. Lwy dobrze się adaptują do wielu środowisk, lecz preferują sawanny bogate w ssaki kopytne, gdzie – obok hieny cętkowanej – są drugim wielkim drapieżnikiem. Zasiedlają również tereny krzaczaste, górskie i półpustynne. W górach Bale w Etiopii populacja lwów żyje na wysokości 4240 m n.p.m.[17] W Afryce Południowej zostały wytępione, z wyjątkiem osobników chronionych w parkach narodowych Krugera i Kalahari Gemsbok.\n" 
                + "Nieliczna obecnie populacja lwów azjatyckich (Panthera leo persica), które w czasach historycznych żyły na Bałkanach, lasach Grecji przez Persję, aż do Indii, występuje współcześnie tylko w lesie Gir w stanie Gujarat w północnych Indiach. W 2005 odnotowano w tym rezerwacie 359 lwów. Rezerwat ma powierzchnię ok. 1412 km²[18]. Ten podgatunek jest krytycznie zagrożony wymarciem.\n"
                + "Większość publikowanych prac na temat lwów opiera się na obserwacjach populacji z Serengeti i Ngorongoro.<br/>";
        String c ="&nbsp Tygrys azjatycki, tygrys (Panthera tigris) – gatunek dużego, drapieżnego ssaka łożyskowego z rodziny kotowatych (Felidae), największy z żyjących współcześnie[8] czterech wielkich, ryczących kotów z rodzaju Panthera, jeden z największych drapieżników lądowych – wielkością ustępuje jedynie niektórym niedźwiedziom. Dorosłe samce osiągają ponad 300 kg masy ciała przy ponad 3 m całkowitej długości. Rekordowa masa ciała samca tygrysa syberyjskiego wynosi 423 kg[9]. Dobrze skacze, bardzo dobrze pływa, poluje zwykle samotnie. Dawniej liczny w całej Azji, zawsze budzący grozę, stał się obiektem polowań dla sportu, pieniędzy lub w odwecie – z powodu zagrożenia, jakie stanowi dla ludzi i zwierząt hodowlanych[10]. Wytępiony w wielu regionach, zagrożony wyginięciem, został objęty programami ochrony. Największa dzika populacja żyje w Indiach. W niektórych regionach Indii tygrysy są uważane za zwierzęta święte.\n" 
                + "Słowo „tygrys” pochodzi od greckiego wyrazu tigris, które z kolei ma najprawdopodobniej irańskie korzenie.\n" 
                + "Został opisany przez Linneusza w 10. edycji Systema Naturae (1758) jako Felis tigris. W 1858 roku rosyjski przyrodnik Nikołaj Siewiercow opisał tego dużego kota pod nazwą Tigris striatus. W 1929 Pocock zaliczył go do rodzaju Panthera.\n" 
                + "Obecnie większość zoologów zgadza się z przynależnością tygrysa do tego właśnie rodzaju. Dokładniej przeprowadzone badania anatomiczne wykazały jednak, że tygrys może być blisko spokrewniony z panterą mglistą. Przynależność rodzajowa tego kota jest więc niepewna. Obecnie prowadzone są szczegółowe badania anatomiczne, genetyczne oraz molekularne, których celem jest ustalenie relacji pokrewieństwa pomiędzy przedstawicielami Pantheriinae."
                + "Filogeneza tygrysów nie została jednoznacznie wyjaśniona. Współczesna wiedza o pochodzeniu tych drapieżników opiera się na niewielkiej ilości materiału kopalnego. Wszystkie żyjące współcześnie duże koty zaliczane są do podrodziny Pantheriinae. Najstarszym znanym gatunkiem o możliwym dużym stopniu pokrewieństwa jest znaleziony w północnych Chinach i na Jawie wczesnoplejstoceńska, mniejsza od tygrysa Panthera palaeosinensis. Najprawdopodobniejszym prekursorem linii kotowatych, z której powstał Panthera tigris, jest wymarła przed kilkoma milionami lat Panthera schreuderi. Nie ma jednak pewności, gdyż jego skamieniałości nie wskazują jednoznacznie na pokrewieństwo ze znanym współcześnie tygrysem[11].\n" 
                + "Kilka milionów lat temu niemal w całej Azji dominował P. t. acutidens, od którego pochodzi tygrys chiński (Panthera tigris amoyensis). Jedna z teorii zakłada, że wszystkie tygrysy, które zasiedlają tereny inne, niż Indonezja, wywodzą się właśnie od tego podgatunku. Około 1,2 miliona lat temu w Indonezji pojawił się Panthera tigris trinilensis (tygrys z Trinil) odkryty na stanowisku archeologicznym Trinil na Jawie. Według większości zoologów jest on przodkiem wszystkich znanych indonezyjskich podgatunków tygrysa i nie wywodzi się od wcześniejszego P. t. acutidens.<br/>" 
                + "Skamieliny tygrysów znajdowano również na Borneo, we wschodniej Beringii i na Sachalinie. W Indiach i północnej Azji tygrys pojawił się pod koniec plejstocenu.";
        x = r.nextInt(3);
        if (x == 1){
                zawartosc = a;
            }
        if (x == 2){
                zawartosc = b;
            }
        if (x == 3){
                zawartosc = c;
            }
    }
    @Override
    public void tworz(){
        
    }
}
