package Strony;
import FabrykaMain.tworzStrony;
import java.util.Random;

public class Informacyjna extends Strona implements tworzStrony {
    public Informacyjna(){
        Random r = new Random();
        int x = 0;
        String a ="&nbspKot domowy (Felis catus, rowniez Felis silvestris catus lub Felis (silvestris) domesticus) to "
                + "udomowiony gatunek ssaka z rzedu drapieznych z rodziny kotowatych. Koty zostaly udomowione okolo 9500 lat temu i sa obecnie najpopularniejszymi zwierzetami domowymi na swiecie. "
                + "Gatunek prawdopodobnie pochodzi od kota nubijskiego, przy czym w Europie krzyzowal sie ze zbikiem. Jest uznawany za gatunek inwazyjny.<br/>"
                + "Przodkiem kota domowego jest kot nubijski – wedlug pogladow wiekszosci wspolczesnych naukowcow roznice pomiedzy kotem domowym i nubijskim sa tak niewielkie, ze naleza one do tego samego podgatunku. Istnieja rozbieznosci w kwestii daty udomowienia kota. Wiekszosc zrodel sugeruje lata od 4000 do 3700 p.n.e., a miejscem, w ktorym mialo do tego dojsc, byla Nubia. "
                + "Istnieja jednak dowody (grob mezczyzny z kotem z Cypru sprzed ok. 7500 r. p.n.e.), ze domestykacja kota zaczela sie znacznie wczesniej i trwala kilka tysiecy lat, a jej miejscem byl obszar Zyznego Polksiezyca. Juz ok. 2000 r. p.n.e. kot byl pospolicie hodowany w Egipcie. Poczatkowo byl obiektem kultu, wiazano go z boginia Bastet, a zwloki kotow mumifikowano. Pozniej zaczeto wykorzystywac go do tepienia gryzoni.\n" 
                + "Wyhodowano wiele ras kota domowego, rozniacych sie ubarwieniem, wielkoscia i dlugoscia wlosow; wspolczesne wzorce niektorych starszych ras znacznie odbiegaja od ich wczesniejszych cech (jak w przypadku kotow perskich czy syjamskich)."
                + "Znaczna liczba kotow domowych zyje samodzielnie w miastach (w Polsce sa to tzw. koty piwniczne lub dachowce).\n"
                + "Koty zyjace na wolnosci dozywaja srednio do 8 lat, natomiast koty trzymane w domu osiagaja wiek do 20 lat. Na dlugosc zycia wplywa szereg czynnikow, takich jak: plec, styl zycia czy zwyczaje. Najdluzej zyjacym kotem wedlug Ksiegi rekordow Guinnessa byla kotka imieniem Creme Puff (1967 do 2005), ktora przezyla 38 lat i 3 dni.\n" 
                + "Male kocieta rozwijaja sie szybko. Staja sie w pelni samodzielne w wieku od 10 do 12 tygodni i wtedy moga trafic do nowych wlascicieli. Gdy maja okolo 3 miesiecy kotka przestaje się nimi interesowac i zmusza je do samodzielnosci. W wieku okolo 5 miesiecy kociaki wymieniaja zeby na stale. Dziecinstwo konczy sie z uzyskaniem dojrzalosci plciowej. W tym okresie moze pojawic się pierwsza ruja, a kot zaczyna oznaczać swoje terytorium.\n"
                + "Wyrazne objawy starosci pojawiaja sie zwykle po 10 roku zycia: coraz czesciej pojawia sie kamien nazebny, oslabia sie wzrok, sluch i wech, staja sie powolne oraz slabe. Stare koty sa bardzo wrazliwe na zmiany srodowiskowe i stres.<br/>";
        String b ="&nbsp Lew afrykanski, lew (Panthera leo) – miesozerny gatunek ssaka ladowego z rodziny kotowatych, drugi po tygrysie – co do wielkosci – wsrod czterech ryczacych wielkich kotow. Jedyny kot zyjacy w zorganizowanych grupach socjalnych, zaliczany do tzw. wielkiej piatki Afryki czyli pieciu najbardziej niebezpiecznych zwierzat afrykanskich (slon, nosorozec, bawol, lew i lampart). Samiec lwa, latwo rozpoznawalny po grzywie, moze wazyc od 150 do 200 kg. Najwiekszy znany samiec wazyl 375 kg, byl to lew o imieniu Simba, xyl on do 1970 roku w Colchester Zoo. "
                + "Samice sa znacznie mniejsze, waza od 120 do 180 kg (najwieksze 185 kg) i nie maja grzywy. Samce zajmują sie zdobywaniem i obroną terytorium oraz ochrona stada i zapladnianiem samic. Samice poluja i opiekuja sie lwiatkami. Lwy zamieszkiwaly niegdys Afryke, Azje i Europe, a jesli uznac lwy amerykanskie za podgatunek Panthera leo to rowniez Ameryke Polnocna i Poludniowa. Wspolczesnie wystepuja tylko w Afryce, gdzie sa narazone na wyginiecie i szczątkowo w Indiach, gdzie ich stan liczebny okreslony zostal jako krytyczny.\n"
                + "Etymologia nazw lew i Panthera leo nie jest jednoznacznie wyjasniona. Slowo leo pochodzi od lacinskiego leo, leonis, ktore z kolei wywodzi sie ze starogreckiego leen. Dalszych zrodel autorzy dopatruja się w jezyku hebrajskim i staroegipskim.\n" 
                + "Lew jako gatunek zostal opisany naukowo przez Linneusza pod nazwa Felis leo Linnaeus, 1758, następnie przeniesiony do rodzaju Leo Brehm, 1829, a w koncu zaliczony przez Pococka do rodzaju Panthera w 1930. Pochodzenie slowa Panthera jest czesto wyjasniane jako zlozenie greckiego pan oznaczajacego wszech i ther oznaczajacego zwierze, co mialoby nawiazywac do dawnego szerokiego zasiegu wystepowania lwow. Online Etymology Dictionary wyjasnienie takie uwaza za etymologie ludowa i dopatruje sie pochodzenia slowa panthera z orientalnych okreslen ubarwienia zwierzecia."
                + "Wielkie koty, do ktorych zaliczany jest lew, wywodza sie z jednej linii ewolucyjnej, okreslanej nazwa Pantherinae. Naleza do niej rodzaje Panthera i Neofelis i Pardofelis. Dotychczas nie znaleziono ich ostatniego wspolnego przodka, ale z badan mtDNA wynika, ze ich linie rozwojowe oddzielily sie ok. 6 mln lat temu. Znalezione slady kopalne sugeruja, ze przedstawiciele kotow podobnych do wspołczesnego lwa pojawili sie w Afryce Wschodniej w poznym pliocenie (5 do 1,8 mln lat temu). Najstarsze szczatki zaliczane do linii rozwojowej lwa, datowane na ok. 3,5 mln lat, odnaleziono w Laetoli w Tanzanii. Niektorzy naukowcy klasyfikuja go do gatunku Panthera leo, ale stanowisko takie nie jest powszechnie akceptowane ze wzgledu na wiele niejasnosci.\n" 
                + "Naukowcy sa zgodni co do tego, ze wlasciwy Panthera leo zył w Afryce co najmniej 1,5 mln lat temu i rozprzestrzenil sie po calym kontynencie. Wczesnoplejstocenskie prymitywne lwy opisywane poczatkowo jako P. l. fossilis pojawily sie we wczesnym i srodkowym plejstocenie, a ok. 700 tysięcy lat temu migrowaly do Europy i Azji. W poznym plejstocenie (100 do 10 tys. lat temu) byly najbardziej rozprzestrzenionym duzym ssakiem ladowym. Zasieg ich występowania obejmowal Afryke, Eurazje, Ameryke Polnocna i Poludniowa. W czasach historycznych (2 tys. lat temu) zamieszkiwaly juz tylko Balkany (Bulgaria, Macedonia i lasy Grecji) przez Persjw az do Indii i prawie cala Afryke.\n" 
                + "Lew byl kiedys – jak wiekszosc wspolczesnych drapieznikow gatunkiem kosmopolitycznym. Gwaltowne przemiany antropogeniczne w przeciagu ostatnich kilku tysiecy lat obecnej epoki holocenskiej spowodowaly wymarcie populacji lwow na wielu obszarach, w wyniku czego lew jest obecnie gatunkiem reliktowym, zagrozonym przede wszystkim ze strony czlowieka.\n" 
                + "Z badan genetycznych wynika, ze niezaleznie wyewoluowaly dwie odrebne linie lwa. Jedna reprezentowana przez wymarle pod koniec ostatniej epoki lodowcowej (ok. 10 tys. lat temu) lwy jaskiniowe i lwy amerykanskie, druga przez wspolczesnego Panthera leo."
                + "Pierwotny zasieg wystepowania lwow obejmowal tereny Eurazji od Portugalii po Indie, wieksza czesc Afryki oraz Ameryke od północy po Peru. Stopniowo eliminowany z Ameryki i Europy, ostatni obszar wystepowania w Europie to Kaukaz, gdzie spotykano go jeszcze w X w. n.e. Pod koniec XIX i na poczatku XX w. wyginely w Afryce Polnocnej i na Bliskim Wschodzie. Z pierwotnego zasiegu zostal wyeliminowany przez czynniki srodowiskowe i dzialalnosc czlowieka i ograniczony wylacznie do terenow Afryki i Indii. Wiekszosc obecnej populacji szacowanej pomiędzy 16000 a 30000 osobnikow wystepuje we wschodniej i poludniowej czesci Afryki.\n" 
                + "Na przekor popularnemu okresleniu \"krol dzungli\" lew jest zwierzeciem otwartych rownin. Mozna go spotkac w calej Afryce, glownie subsaharyjskiej, z wyjatkiem terenow pustynnych i lasow rownikowych. Lwy dobrze sie adaptuja do wielu srodowisk, lecz preferuja sawanny bogate w ssaki kopytne, gdzie obok hieny cetkowanej sa drugim wielkim drapieznikiem. Zasiedlaja rowniez tereny krzaczaste, gorskie i pólpustynne. W gorach Bale w Etiopii populacja lwow zyje na wysokosci 4240 m n.p.m. W Afryce Poludniowej zostaly wytepione, z wyjatkiem osobnikow chronionych w parkach narodowych Krugera i Kalahari Gemsbok.\n" 
                + "Nieliczna obecnie populacja lwów azjatyckich (Panthera leo persica), które w czasach historycznych żyły na Bałkanach, lasach Grecji przez Persję, aż do Indii, występuje współcześnie tylko w lesie Gir w stanie Gujarat w północnych Indiach. W 2005 odnotowano w tym rezerwacie 359 lwów. Rezerwat ma powierzchnię ok. 1412 km kwadratowych. Ten podgatunek jest krytycznie zagrożony wymarciem.\n"
                + "Większość publikowanych prac na temat lwów opiera się na obserwacjach populacji z Serengeti i Ngorongoro.<br/>";
        String c ="&nbsp Tygrys azjatycki, tygrys (Panthera tigris) – gatunek dużego, drapieżnego ssaka łożyskowego z rodziny kotowatych (Felidae), największy z żyjących współcześnie[8] czterech wielkich, ryczących kotów z rodzaju Panthera, jeden z największych drapieżników lądowych – wielkością ustępuje jedynie niektórym niedźwiedziom. Dorosłe samce osiągają ponad 300 kg masy ciała przy ponad 3 m całkowitej długości. Rekordowa masa ciała samca tygrysa syberyjskiego wynosi 423 kg[9]. Dobrze skacze, bardzo dobrze pływa, poluje zwykle samotnie. Dawniej liczny w całej Azji, zawsze budzący grozę, stał się obiektem polowań dla sportu, pieniędzy lub w odwecie – z powodu zagrożenia, jakie stanowi dla ludzi i zwierząt hodowlanych[10]. Wytępiony w wielu regionach, zagrożony wyginięciem, został objęty programami ochrony. Największa dzika populacja żyje w Indiach. W niektórych regionach Indii tygrysy są uważane za zwierzęta święte.\n" 
                + "Słowo „tygrys” pochodzi od greckiego wyrazu tigris, które z kolei ma najprawdopodobniej irańskie korzenie.\n" 
                + "Został opisany przez Linneusza w 10. edycji Systema Naturae (1758) jako Felis tigris. W 1858 roku rosyjski przyrodnik Nikołaj Siewiercow opisał tego dużego kota pod nazwą Tigris striatus. W 1929 Pocock zaliczył go do rodzaju Panthera.\n" 
                + "Obecnie większość zoologów zgadza się z przynależnością tygrysa do tego właśnie rodzaju. Dokładniej przeprowadzone badania anatomiczne wykazały jednak, że tygrys może być blisko spokrewniony z panterą mglistą. Przynależność rodzajowa tego kota jest więc niepewna. Obecnie prowadzone są szczegółowe badania anatomiczne, genetyczne oraz molekularne, których celem jest ustalenie relacji pokrewieństwa pomiędzy przedstawicielami Pantheriinae."
                + "Filogeneza tygrysów nie została jednoznacznie wyjaśniona. Współczesna wiedza o pochodzeniu tych drapieżników opiera się na niewielkiej ilości materiału kopalnego. Wszystkie żyjące współcześnie duże koty zaliczane są do podrodziny Pantheriinae. Najstarszym znanym gatunkiem o możliwym dużym stopniu pokrewieństwa jest znaleziony w północnych Chinach i na Jawie wczesnoplejstoceńska, mniejsza od tygrysa Panthera palaeosinensis. Najprawdopodobniejszym prekursorem linii kotowatych, z której powstał Panthera tigris, jest wymarła przed kilkoma milionami lat Panthera schreuderi. Nie ma jednak pewności, gdyż jego skamieniałości nie wskazują jednoznacznie na pokrewieństwo ze znanym współcześnie tygrysem[11].\n" 
                + "Kilka milionów lat temu niemal w całej Azji dominował P. t. acutidens, od którego pochodzi tygrys chiński (Panthera tigris amoyensis). Jedna z teorii zakłada, że wszystkie tygrysy, które zasiedlają tereny inne, niż Indonezja, wywodzą się właśnie od tego podgatunku. Około 1,2 miliona lat temu w Indonezji pojawił się Panthera tigris trinilensis (tygrys z Trinil) odkryty na stanowisku archeologicznym Trinil na Jawie. Według większości zoologów jest on przodkiem wszystkich znanych indonezyjskich podgatunków tygrysa i nie wywodzi się od wcześniejszego P. t. acutidens.<br/>" 
                + "Skamieliny tygrysów znajdowano również na Borneo, we wschodniej Beringii i na Sachalinie. W Indiach i północnej Azji tygrys pojawił się pod koniec plejstocenu.";
        x = r.nextInt(3)+1;
        if (x == 1){
                zawartosc = a;
            }
        if (x == 2){
                zawartosc = b;
            }
        if (x == 3){
                zawartosc = c;
            }
    }
    @Override
    public void tworz(){
        
    }
}
